server:
  port: 8086
spring:
  application:
    name: request-ms
  data:
    mongodb:
      uri: mongodb+srv://bassem:bassem@authentication.6mvbj9d.mongodb.net/?retryWrites=true&w=majority
      database: requests
      auto-index-creation: true
  main:
    allow-circular-references: true

  profiles:
    active: native
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      defaultZone: http://172.17.0.2:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
management:
  info:
    env:
      enabled: true
